Trying to Make Travis Happy

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -69,12 +69,15 @@ script:
             pipenv run python src/shared/CanMsgs/generate_c_code_from_sym.py;
             # Show the diff
             #git --no-pager diff;
-            # Check if there was a non-zero diff
+            # Check if there was a non-zero diff (disable set -e for this) so
+            # we can capture the result and print a error msg
+            set +e
             git diff-index --quiet HEAD --
             git_diff_result=$?
+            set -e
             if [ $git_diff_result -ne 0 ]; then
                 echo "Git diff was non-zero! Re-run generate_c_code_from_sym.py to generate C code from the .sym file.;"
-                #return 1;
+                return 1;
             else
                 echo "ELSE"
             fi
