Cleaned Up Formatting Scripts (#320)
* Cleaned Up Formatting Scripts

* Added Some CMake-related files to the `.gitignore`

* Broke Formatting

* Revert "Broke Formatting"

This reverts commit 70f346d2af52c83003a2ec0afd55f71f9ce969b9.

* Changed Python Executable Directory Detection To Use Absolute Path

* Broke Formatting:

* Revert "Broke Formatting:"

This reverts commit 860d31b7d9079c30d2170d0925e058554b3a3478.

* Fixed fix_formatting Runtime Error

* Broke Formatting

* Fixed Formatting

* Import sys in fix_formatting.py

* Broke Formatting

* Fixed Formatting

* Broke formatting

* Misc. Cleanup in travis.yml (formatting still broken

* Fixed formatting

* Removed Extra Space

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -69,7 +69,27 @@ script:
     - |
       if [ "$RUN_FORMATTING_CHECKS" = "true" ]; then 
             cd clang-format;
-            echo -e "Y" | python check_formatting_CI.py;
+            echo -e "Y" | python fix_formatting.py;
+            # Show the diff
+            git --no-pager diff;
+            # Check if there was a non-zero diff (disable set -e for this) so
+            # we can capture the result and print a error msg (otherwise a
+            # non-zero result would just cause this script to exit)
+            set +e
+            git diff-index --quiet HEAD --
+            git_diff_result=$?
+            set -e
+            if [ $git_diff_result -ne 0 ]; then
+                echo ""
+                echo ""
+                echo "#########################"
+                echo "FAILED - Git diff was non-zero!"
+                echo "Run `clang_format/fix_formatting.py` to format your code properly!,"
+                echo "#########################"
+                return 1;
+            else
+                echo "PASSED - Code is correctly formatted!"
+            fi
       fi
     - |
       if [ "$GENERATE_CODE_FROM_SYM" = "true" ]; then 
